apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devops-notes

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - mysql.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml
